### PR TITLE
Discovery: more consistent query functions

### LINKED ISSUE #12: Query functions overlap a lot
Now the Discovery.hs module is not great structure-wise, especially when query through a folder, different default folders. 
There are lots of overlaps between queryJKUPDD and queryOneSynth for example.

### LINKED ISSUE #13: Tests: fix failing examples
Also, re-enable them on `.travis.yml`

### PR DESCRIPTION
**Pull request by omelkonian**
* Avoid repetition in Discovery.hs (closes #12)

  * Commenting out failing tests + re-enable on Travis (closes #13)

  * README: Fix badge for Hackage

### CODE REVIEW

**Comment by irisyupingren** [comment]
Thanks for cleaning it up!
I changed to a tuple because I'm not familiar with the :@ operator. Where can I find more about it?

**Comment by omelkonian** [comment]
Oh, it's defined there for the first time (with the `data` keyword). It might be confusing that it is an infix constructor for the datatype `Query a`.

**Comment by omelkonian** [comment]
To clarify, imagine you could define tuple yourself like this (instead of `,`, we can use the infix `:×:`):
```haskell
data Tuple A B = A :×: B

t : Tuple Int String
t = 5 :×: "five"
```

**Comment by irisyupingren** [comment]
Ah of course! All clear now thank you!

**Pull request merged**
